random-xs:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
random-xs-clustered:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":32, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":50, "T":8}]
msspacev-1M:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msturing-1M:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":50, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":300, "T":16},
             {"Ls":100, "T":16}]
msspacev-10M:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]
msturing-10M-clustered:
    low_memory2: 
      docker-tag: neurips23-streaming-low_memory2
      module: neurips23.streaming.low_memory2.low_memory2
      constructor: low_memory2
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"R":64, "L":50, "insert_threads":16, "consolidate_threads":16}]
          query-args: |
            [{"Ls":100, "T":16}]